
export const stagingImports = {
  //Stragin Clientes
  clientes: {
    label: "Clientes",
    table: "stg_clientes_csv",
    skipLines: 5,
    columns: [
      "cliente_documento",
      "tipo_documento",
      "tipo_cliente",
      "cliente_nombre",
      "apellido_contacto",
      "nombre_contacto",
      "direccion",
      "departamento",
      "provincia",
      "distrito",
      "telefono_fijo",
      "celular",
      "telefono_oficina",
      "red_privada",
      "email_personal",
      "email_trabajo",
      "email_see",
      "genero",
      "estado_civil",
      "fecha_nacimiento",
      "grupo_cliente",
      "forma_pago",
      "acepta_tratamiento",
    ],
  },

  //Stagin Cliente Servicios
  clientes_servicio: {
    label: "Clientes de Servicio",
    table: "stg_clientes_servicio_csv",
    skipLines: 5,
    columns: [
      "concesionario",
      "local_nombre",
      "cliente_nombre",
      "contacto",
      "tipo_cliente",
      "telefono_fijo",
      "celular",
      "oficina",
      "correo",
      "asesor",
      "dni",
      "fecha_apertura",
      "placa",
      "grupo_servicio",
      "clase_ot",
      "tipo_ot",
      "kilometraje",
      "anio_fabricacion",
      "tratamiento_datos",
      "fecha_entrega",
      "grupo_cliente",
      "nro_ot",
      "subtipo_ot",
      "campania_externa",
      "marca",
      "modelo",
      "version",
      "color",
    ],
  },

  //Stagin Ordenes de Trabajo

  ordenes_trabajo: {
    label: "Órdenes de Trabajo",
    table: "orden_trabajo",
    skipLines: 5,
    // Si vuelves a subir un CSV que se solapa con uno ya cargado (mismo
    // nro_orden + actividad), actualiza esa fila en vez de duplicarla.
    upsert: true,
    columns: [
      "local_nombre",
      "nro_orden",
      "fec_apertura",
      "fec_cierre",
      "fec_entrega",
      "fec_factura",
      "nro_factura",
      "estado",
      "cliente_documento",
      "cliente_nombre",
      "placa",
      "chasis",
      "motor",
      "marca",
      "modelo",
      "version",
      "anio_fabricacion",
      "anio_modelo",
      "kilometraje_real",
      "grupo_servicio",
      "clase_ot",
      "tipo_ot",
      "asesor",
      "tecnico_asignado",
      "origen_codigo",
      "codigo_actividad",
      "actividad",
      "cantidad",
      "moneda",
      "costo",
      "valor_venta",
      "precio_venta",
      "utilidad",
      "tecnico_actividad",
      "total_min_pla",
      "total_min_con",
      "contacto",
      "telefono",
      "correo",
      "grupo_cliente",
      "tipo_danio",
      "nro_panos",
      "horas_hombre",
      "departamento",
      "provincia",
      "distrito",
      "nro_cita",
      "man_rep",
      "subtipo_ot",
      "campania_externa",
      "recomendaciones",
    ],
  },

  registro_venta: {
    label: "Registro de Venta por Local",
    table: "registro_venta",
    skipLines: 5,
    // Igual que ordenes_trabajo: al resubir un CSV del mismo periodo (tu
    // costumbre de cargar desde enero hasta hoy cada vez), actualiza los
    // documentos que ya existen (mismo nro_documento + local) en vez de
    // duplicarlos.
    upsert: true,
    columns: [
      "fec_documento",
      "tipo_documento",
      "nro_documento",
      "cliente_documento",
      "cliente_nombre",
      "moneda",
      "moneda_usd",
      "valor_gravado",
      "valor_exonerado",
      "valor_inafecto",
      "impuesto",
      "precio_venta",
      "clase_venta",
      "asesor",
      "estado",
      "operacion_relacionada",
      "asesor_operacion",
      "forma_pago",
      "flujo_caja",
      "saldo_cancelar",
      "estado_sunat",
      "fec_registro_documento",
      "local_nombre",
      "contenido_documento",
    ],
  },
};
