
export const stagingImports = {
  seguimiento_mantenimiento: {
    label: "Seguimiento de Mantenimientos",
    table: "seguimiento_mantenimiento",
    format: "xlsx",
    skipLines: 5,
    // El reporte es acumulativo y el ERP va marcando ATENDIDO sobre filas
    // previas, asi que se hace upsert por (local + placa + fecha propuesta).
    // Nada de replacePeriod: borraria el seguimiento de lo que no venga en
    // el archivo de ese dia.
    upsert: true,
    // La sede se declara una sola vez, en la fila 2 del reporte.
    localFromHeader: [1, 2],
    dateColumn: "fec_servicio_prop",
    // Estado vacio = pendiente: tiene que quedar NULL, no cadena vacia.
    emptyAsNull: true,
    // Tras cargar, resuelve asesora_asignada con las reglas de cartera.
    resolverAsesora: true,
    columns: [
      "local_nombre",
      "placa",
      "marca",
      "modelo",
      "version",
      "cliente_documento",
      "cliente_nombre",
      "contacto",
      "telefono",
      "fec_penul_servicio",
      "fec_ult_servicio",
      "ultimo_asesor",
      "recomendacion",
      "servicio_prop_km",
      "fec_servicio_prop",
      "estado",
      "fec_atencion",
      "vehiculo_alquilado",
      "contacto_alquiler",
      "ref_contacto",
    ],
  },

  detalle_factura_ot: {
    label: "Detalle de Facturas por OT",
    table: "detalle_factura_ot",
    format: "csv_or_xlsx",
    parser: "detalle_factura_ot",
    upsert: true,
    replacePeriod: true,
    replacePeriodColumn: "fec_emision",
  },

  ordenes_trabajo: {
    label: "Órdenes de Trabajo",
    table: "orden_trabajo",
    format: "csv_or_xlsx",
    skipLines: 5,
    // Si vuelves a subir un CSV que se solapa con uno ya cargado (mismo
    // nro_orden + actividad), actualiza esa fila en vez de duplicarla.
    upsert: true,
    // El reporte de OT representa el estado vigente. Se reemplaza la sede y
    // rango importados para retirar OT que ya no aparecen (por ejemplo anuladas).
    replacePeriod: true,
    replacePeriodColumn: "fec_apertura",
    columns: [
      "local_nombre",
      "nro_orden",
      "fec_apertura",
      "fec_cierre",
      "fec_entrega",
      "fec_factura",
      "nro_factura",
      "estado",
      "cliente_documento",
      "cliente_nombre",
      "placa",
      "chasis",
      "motor",
      "marca",
      "modelo",
      "version",
      "anio_fabricacion",
      "anio_modelo",
      "kilometraje_real",
      "grupo_servicio",
      "clase_ot",
      "tipo_ot",
      "asesor",
      "tecnico_asignado",
      "origen_codigo",
      "codigo_actividad",
      "actividad",
      "cantidad",
      "moneda",
      "costo",
      "valor_venta",
      "precio_venta",
      "utilidad",
      "valor_venta_repuestos",
      "valor_venta_servicios",
      "tecnico_actividad",
      "total_min_pla",
      "total_min_con",
      "contacto",
      "telefono",
      "correo",
      "grupo_cliente",
      "tipo_danio",
      "nro_panos",
      "horas_hombre",
      "departamento",
      "provincia",
      "distrito",
      "nro_cita",
      "man_rep",
      "subtipo_ot",
      "campania_externa",
      "recomendaciones",
    ],
  },

  registro_venta: {
    label: "Registro de Venta por Local",
    table: "registro_venta",
    format: "csv_or_xlsx",
    skipLines: 5,
    // Igual que ordenes_trabajo: al resubir un CSV del mismo periodo (tu
    // costumbre de cargar desde enero hasta hoy cada vez), actualiza los
    // documentos que ya existen (mismo nro_documento + local) en vez de
    // duplicarlos.
    upsert: true,
    // El registro vigente reemplaza la sede y rango importados para no conservar
    // documentos que desaparecieron del reporte actualizado.
    replacePeriod: true,
    replacePeriodColumn: "fec_documento",
    columns: [
      "fec_documento",
      "tipo_documento",
      "nro_documento",
      "cliente_documento",
      "cliente_nombre",
      "moneda",
      "moneda_usd",
      "valor_gravado",
      "valor_exonerado",
      "valor_inafecto",
      "impuesto",
      "precio_venta",
      "clase_venta",
      "asesor",
      "estado",
      "operacion_relacionada",
      "asesor_operacion",
      "forma_pago",
      "flujo_caja",
      "saldo_cancelar",
      "estado_sunat",
      "fec_registro_documento",
      "local_nombre",
      "contenido_documento",
    ],
  },
};
