// Mapeo Familia (real, tal como sale en los 4 reportes de almacen) ->
// Sistema + Sub-Sistema, con criterio de empresa automotriz. Es propuesta
// mia — revisar y ajustar antes de usarlo en serio para codificar.
export const SISTEMAS = [
  ['Motor', 'M'],
  ['Chasis', 'C'],
  ['Electricidad', 'E'],
  ['Suspensión', 'S'],
  ['Transmisión', 'T'],
  ['Frenos', 'F'],
  ['Accesorios', 'A'],
  ['Dirección', 'D'],
  ['Carrocería', 'CR'],
  ['Refrigeración', 'RF'],
  ['Combustible', 'CB'],
  ['Embrague', 'EM'],
  ['Aire acondicionado', 'AC'],
  ['Escape', 'ES'],
  ['General', 'GN'],
  ['No aplica', 'NA'],
];

export const SUBSISTEMAS = [
  ['Admisión', 'AD'],
  ['Carrocería (exterior)', 'CA'],
  ['Luces', 'LU'],
  ['Amortiguación', 'AM'],
  ['Caja diferencial', 'CD'],
  ['ABS, EBD, etc.', 'AB'],
  ['Hidráulica', 'HI'],
  ['EPS (dirección eléctrica)', 'EP'],
  ['Lubricación', 'LB'],
  ['Filtros', 'FL'],
  ['Encendido', 'EN'],
  ['Vidrios y espejos', 'VE'],
  ['Componentes de suspensión', 'CS'],
  ['Caja de cambios', 'CC'],
  ['Motor interno', 'MOI'],
  ['Arranque y carga', 'AR'],
  ['Cremallera y terminales (dirección)', 'CT'],
  ['General / consumibles', 'GC'],
  ['No aplica', 'NA'],
];

// clave = Familia en MAYUSCULAS tal cual sale del reporte. valor = [Sistema, Sub-Sistema o null]
export const FAMILIA_A_SISTEMA = {
  'OTROS REPUESTOS': ['General', 'General / consumibles'],
  'VARIOS': ['General', 'General / consumibles'],
  'ACCESORIOS': ['Accesorios', 'General / consumibles'],
  'SPOILER': ['Carrocería', 'Carrocería (exterior)'],
  'OTROS SIN DSCTO': ['General', 'General / consumibles'],
  'FILTRO DE AIRE': ['Motor', 'Filtros'],
  'PASTILLAS': ['Frenos', null],
  'FARO': ['Electricidad', 'Luces'],
  'HERRAMIENTAS': ['General', 'General / consumibles'],
  'RETENES': ['Motor', 'Motor interno'],
  'CAUTIVO MOTOR': ['Motor', 'Motor interno'],
  'AMORTIGUADOR': ['Suspensión', 'Amortiguación'],
  'FILTRO DE ACEITE': ['Motor', 'Filtros'],
  'CAUTIVO ELECTRICO': ['Electricidad', null],
  'FAJAS': ['Motor', null],
  'CAUTIVO ELECTRICO Y COLISION': ['Electricidad', null],
  'FILTRO DE COMBUSTIBL': ['Combustible', 'Filtros'],
  'CAUTIVO SUSP, DIREC Y FRENO': ['Suspensión', null],
  'ARTICULO QUIMICO': ['General', 'Lubricación'],
  'EMPAQUE DE MOTOR VARIOS Y TAPONES': ['Motor', 'Motor interno'],
  'PARACHOQUES': ['Carrocería', 'Carrocería (exterior)'],
  'BUJIAS': ['Electricidad', 'Encendido'],
  'TERMINALES DIRECCION': ['Dirección', 'Cremallera y terminales (dirección)'],
  'ZAPATAS': ['Frenos', null],
  'PASTILLAS (MVP)': ['Frenos', null],
  'PLUMILLAS Y JEBES': ['Accesorios', null],
  'CHASIS CABINA': ['Chasis', null],
  'OTROS QUIMICOS': ['General', 'Lubricación'],
  'MANGUERA': ['Refrigeración', null],
  'MASCARA': ['Carrocería', 'Carrocería (exterior)'],
  'TRAPECIO': ['Suspensión', 'Componentes de suspensión'],
  'MOTOR CAUTIVO': ['Motor', 'Motor interno'],
  'SOPORTE DE MOTOR': ['Motor', null],
  'COLLARIN': ['Embrague', null],
  'CAUTIVO CAJA DE CAMBIOS': ['Transmisión', 'Caja de cambios'],
  'BOMBA DE ACEITE Y AC': ['Motor', 'Lubricación'],
  'CHASIS DIFERENCIAL': ['Transmisión', 'Caja diferencial'],
  'FILTRO DE ACEITE(MVP': ['Motor', 'Filtros'],
  'BOCINA': ['Suspensión', 'Componentes de suspensión'],
  'ESPEJOS': ['Carrocería', 'Vidrios y espejos'],
  'PI': ['General', 'General / consumibles'],
  'RADIADOR': ['Refrigeración', null],
  'BOMBA DE AGUA Y ACCE': ['Refrigeración', null],
  'TERMOSTATO': ['Refrigeración', null],
  'SUSP.DIRECC. Y FRENO': ['Suspensión', null],
  'FAJA DE DISTRIBUCION': ['Motor', 'Motor interno'],
  'DISTRIBUIDOR + PARTES': ['Electricidad', 'Encendido'],
  'DISCO DE EMBRAGUE': ['Embrague', null],
  'LUNAS': ['Carrocería', 'Vidrios y espejos'],
  'CAUTIVO RADIADOR': ['Refrigeración', null],
  'CHASIS DIRECCION': ['Dirección', null],
  'COLLARIN EMBRAGUE': ['Embrague', null],
  'JGO. DE EMPAQUE MOTO': ['Motor', 'Motor interno'],
  'GUARDAFANGO': ['Carrocería', 'Carrocería (exterior)'],
  'PLATO DE EMBRAGUE': ['Embrague', null],
  'EMBLEMA': ['Carrocería', 'Carrocería (exterior)'],
  'VENTILADOR+MOTOR DE VENT': ['Refrigeración', null],
  'PUERTA Y COMPUERTA': ['Carrocería', 'Carrocería (exterior)'],
  'CABINA Y ARMAZON DE CABINA': ['Carrocería', 'Carrocería (exterior)'],
  'TAMBOR DE FRENO': ['Frenos', null],
  'TAPA RADIADOR': ['Refrigeración', null],
  'ACEITE DE TRANSMISION': ['Transmisión', 'Lubricación'],
  'POLEA  MOTOR': ['Motor', 'Motor interno'],
  'ROTULAS': ['Suspensión', 'Componentes de suspensión'],
  'ANILLOS': ['Motor', 'Motor interno'],
  'SOPORTE DE SUSPENSION': ['Suspensión', 'Componentes de suspensión'],
  'BARRA ESTABILIZADORA': ['Suspensión', 'Componentes de suspensión'],
  'CAJA MACANICA': ['Transmisión', 'Caja de cambios'],
  'ACEITE GASOLINERO': ['General', 'Lubricación'],
  'CADENAS': ['Motor', 'Motor interno'],
  'PARABRISAS': ['Carrocería', 'Vidrios y espejos'],
  'PANELES Y PILARES': ['Carrocería', 'Carrocería (exterior)'],
  'CHASIS ANGULO': ['Chasis', null],
  'BOCAMAZA': ['Suspensión', 'Componentes de suspensión'],
  'TEMPLADOR': ['Motor', 'Motor interno'],
  'CREMALLERA DE DIRECC': ['Dirección', 'Cremallera y terminales (dirección)'],
  'HORQUILLA EMBRAGUE': ['Embrague', null],
  'CAPOT': ['Carrocería', 'Carrocería (exterior)'],
  'O-RING': ['Motor', null],
  'ARRANCADOR': ['Electricidad', 'Arranque y carga'],
  'CHASIS TRANSMISION': ['Transmisión', null],
  'SCP': ['General', 'General / consumibles'],
  'VALVULAS': ['Motor', 'Motor interno'],
  'VALVULA PSV': ['Motor', 'Motor interno'],
  'RESORTE SUSPENSION': ['Suspensión', 'Componentes de suspensión'],
  'CA': ['General', 'General / consumibles'],
  'ACEITE PETROLERO': ['General', 'Lubricación'],
  'BOMBA DE EMBRAGUE Y': ['Embrague', null],
  'GUARDAPOLVO PALIER': ['Transmisión', null],
  'GUIAS DE VALVULAS': ['Motor', 'Motor interno'],
  'CILINDRO FRENO': ['Frenos', null],
  'ESCAPE': ['Escape', null],
  'BOMBA DE GASOLINA': ['Combustible', null],
  'COJINETE DE MOTOR': ['Motor', 'Motor interno'],
  'ACCESORIOS DE FRENOS': ['Frenos', null],
  'NUEVA FAMILIA CAMBIAR DESC': ['General', 'General / consumibles'],
  'RAMAL DE MOTOR': ['Electricidad', null],
  'ALTERNADOR': ['Electricidad', 'Arranque y carga'],
  'COMBO HINO': ['General', 'General / consumibles'],
  'VALVULA (LEVAS)': ['Motor', 'Motor interno'],
  'TANQUE RESERVA AGUA (Y TAPA)': ['Refrigeración', null],
  'CONCENTRADOR': ['General', 'General / consumibles'],
  'CONDENSADOR': ['Aire acondicionado', null],
  'AIRE ACONDICIONADO': ['Aire acondicionado', null],
  'ACEITE GASOLINERO 1/': ['General', 'Lubricación'],
  'VARIOS SUSP': ['Suspensión', 'Componentes de suspensión'],
  'CABLE DE BUJIA': ['Electricidad', 'Encendido'],
  'CARTER MOTOR': ['Motor', 'Motor interno'],
  'MOLDURA (POST YARIS)': ['Carrocería', 'Carrocería (exterior)'],
  'BRIDA AGUA': ['Refrigeración', null],
  'COMPUTADORAS': ['Electricidad', 'Arranque y carga'],
  'CHASIS FRENO': ['Frenos', null],
  'REPUESTOS ESPECIALES': ['General', 'General / consumibles'],
  'TEMPLADORES Y POLEAS': ['Motor', 'Motor interno'],
  'VOLANTE': ['Dirección', null],
  'CRUCETA DE CARDAN': ['Transmisión', null],
  'PISTONES': ['Motor', 'Motor interno'],
  'CHASIS SUSPENSION Y FRENO': ['Suspensión', null],
  'BOTON CLAXON (CON AI': ['Electricidad', null],
  'ACEITE DIFERENCIAL': ['Transmisión', 'Lubricación'],
  'LLAVES': ['General', 'General / consumibles'],
  'BOMBA DE SERVO DIREC': ['Dirección', null],
  'TAPA DE ACEITE': ['Motor', 'Motor interno'],
  'TAPA BALANCINES/DISTRIBUIDOR': ['Motor', 'Motor interno'],
  'LIMPIA INYECTOR': ['Combustible', null],
  'BALDES DE HINO': ['General', 'General / consumibles'],
  'BOMBA DE FRENO Y ACC': ['Frenos', null],
  'CAUTIVO DIFERENCIAL': ['Transmisión', 'Caja diferencial'],
  'ARO': ['Suspensión', null],
  'CHASIS SUSPENSION': ['Suspensión', null],
  'PAQUETE DE MUELLES': ['Suspensión', 'Componentes de suspensión'],
  'SOPORTE RADIADOR': ['Refrigeración', null],
  'ACEITE PETROLERO 1/4': ['General', 'Lubricación'],
  'KIT SECADOR': ['Aire acondicionado', null],
  'BOTON CLAXON (CON AIRBAG)': ['Electricidad', null],
  'KIT DE EMPAQUES (RUEDA)': ['Frenos', null],
  'PLATINO': ['Electricidad', 'Encendido'],
  'JEBE DE PEDAL': ['General', 'General / consumibles'],
  'EJE DE PALIER': ['Transmisión', null],
  'CAJA DE TIMON MECANI': ['Dirección', 'Cremallera y terminales (dirección)'],
  'MICAS': ['Carrocería', 'Vidrios y espejos'],
  'ACEITE TRANSFERENCIA': ['Transmisión', 'Lubricación'],
  'CILINDRO ACEITE PETROLEO': ['General', 'General / consumibles'],
  'INYECTORES': ['Combustible', null],
  'CAJA AUTOMATICA': ['Transmisión', 'Caja de cambios'],
  'TRANSMISION MECANICA': ['Transmisión', 'Caja de cambios'],
  'VALVULA DE AIRE': ['General', 'General / consumibles'],
  'CILINDRO ACEITE GASOLINERO': ['General', 'General / consumibles'],
  'CAUTIVOS EMBRAGUE': ['Embrague', null],
  'INTERCOOLER': ['Refrigeración', null],
  'TAPA MALETERA': ['Carrocería', 'Carrocería (exterior)'],
  'GALON GASOLINERO 10W': ['General', 'Lubricación'],
  'BALANCINES Y EJE DE BALANCINES': ['Motor', 'Motor interno'],
  'JGO. GRILLETES DE MUELLE': ['Suspensión', 'Componentes de suspensión'],
  'ANTICONGELANTE': ['Refrigeración', null],
  'CULATAS': ['Motor', 'Motor interno'],
  'PRE-CAMARA': ['Motor', 'Motor interno'],
  'SEMIARMADOS': ['General', 'General / consumibles'],
  'MONTAJE CILINDRO DE FRENO': ['Frenos', null],
  'ENGRANAJE+PI': ['Transmisión', null],
  'ALZAVALVULA': ['Motor', 'Motor interno'],
  'COLADOR ACEITE': ['Motor', 'Lubricación'],
  'VARILLA MEDIDOR': ['Motor', 'Motor interno'],
  'CONJ PURIFICADOR': ['Motor', 'Filtros'],
  'TURBO': ['Motor', null],
  'COMMON RAIL': ['Combustible', null],
  'CUBIERTA DE EMBRAGUE': ['Embrague', null],
  'CAJA DE TRANSFERENCI': ['Transmisión', 'Caja de cambios'],
  'TECHO': ['Carrocería', 'Carrocería (exterior)'],
  'COMPONENTES HIBRIDOS': ['Electricidad', null],
  'VARILLA': ['General', 'General / consumibles'],
  'MANUALES/CATALOGOS': ['General', 'General / consumibles'],
  'CRUCETA': ['Transmisión', null],
};

export function clasificar(familiaRaw) {
  const familia = (familiaRaw || '').toString().trim().toUpperCase();
  return FAMILIA_A_SISTEMA[familia] || ['General', 'General / consumibles'];
}
