// Codigo curado por marca de vehiculo, para reemplazar los codigos
// autogenerados por iniciales. Cubre las 48 marcas reales que aparecen en
// los 4 reportes de almacen (Trujillo/Callao), ordenadas por frecuencia.
export const MARCA_CODIGOS = {
  TOYOTA: 'TO',
  NISSAN: 'NI',
  HYUNDAI: 'HY',
  PEUGEOT: 'PE',
  CHEVROLET: 'CH',
  KIA: 'KI',
  MITSUBISHI: 'MI',
  HINO: 'HI',
  FORD: 'FO',
  SUZUKI: 'SZ',
  RAM: 'RA',
  JAC: 'JA',
  CITROEN: 'CI',
  VOLKSWAGEN: 'VW',
  MAZDA: 'MZ',
  'GREAT WALL': 'GW',
  MAXUS: 'MX',
  RENAULT: 'RE',
  HONDA: 'HO',
  CHANGAN: 'CA',
  FIAT: 'FI',
  SHINERAY: 'SH',
  MG: 'MG',
  JEEP: 'JE',
  HAVAL: 'HA',
  SUBARU: 'SU',
  'MERCEDES BENZ': 'MB',
  CHERY: 'CY',
  VOLVO: 'VO',
  DFSK: 'DF',
  BMW: 'BM',
  FOTON: 'FT',
  ISUZU: 'IS',
  BAIC: 'BA',
  DAIHATSU: 'DA',
  FUSO: 'FU',
  AUDI: 'AU',
  'DONG FENG': 'DG',
  GEELY: 'GE',
  LEXUS: 'LX',
  MAHINDRA: 'MA',
  JETOUR: 'JT',
  SOUEAST: 'SE',
  CUPRA: 'CU',
  DODGE: 'DO',
  JAGUAR: 'JG',
  FORLAND: 'FL',
  CHANGHE: 'CG',
};
