SET NAMES utf8mb4;

-- Estas 3 tablas no tenian script en el repo. orden_trabajo ya existia en
-- la base de Gerson (se documenta aqui tal cual esta hoy); stg_clientes_csv
-- y stg_clientes_servicio_csv NUNCA se crearon: las opciones "Maestro de
-- clientes" y "Clientes de servicio / vehiculos" del importador fallan con
-- error SQL si se usan hoy. Este script las deja listas.

CREATE TABLE IF NOT EXISTS orden_trabajo (
  local_nombre varchar(100) DEFAULT NULL,
  nro_orden varchar(50) DEFAULT NULL,
  fec_apertura varchar(30) DEFAULT NULL,
  fec_cierre varchar(30) DEFAULT NULL,
  fec_entrega varchar(30) DEFAULT NULL,
  fec_factura varchar(30) DEFAULT NULL,
  nro_factura varchar(50) DEFAULT NULL,
  estado varchar(40) DEFAULT NULL,
  cliente_documento varchar(30) DEFAULT NULL,
  cliente_nombre varchar(180) DEFAULT NULL,
  placa varchar(20) DEFAULT NULL,
  chasis varchar(80) DEFAULT NULL,
  motor varchar(80) DEFAULT NULL,
  marca varchar(80) DEFAULT NULL,
  modelo varchar(80) DEFAULT NULL,
  version varchar(150) DEFAULT NULL,
  anio_fabricacion varchar(10) DEFAULT NULL,
  anio_modelo varchar(10) DEFAULT NULL,
  kilometraje_real varchar(30) DEFAULT NULL,
  grupo_servicio varchar(120) DEFAULT NULL,
  clase_ot varchar(120) DEFAULT NULL,
  tipo_ot varchar(120) DEFAULT NULL,
  asesor varchar(120) DEFAULT NULL,
  tecnico_asignado varchar(120) DEFAULT NULL,
  origen_codigo varchar(80) DEFAULT NULL,
  codigo_actividad varchar(80) DEFAULT NULL,
  actividad varchar(250) DEFAULT NULL,
  cantidad varchar(30) DEFAULT NULL,
  moneda varchar(20) DEFAULT NULL,
  costo varchar(30) DEFAULT NULL,
  valor_venta varchar(30) DEFAULT NULL,
  precio_venta varchar(30) DEFAULT NULL,
  utilidad varchar(30) DEFAULT NULL,
  tecnico_actividad varchar(120) DEFAULT NULL,
  total_min_pla varchar(30) DEFAULT NULL,
  total_min_con varchar(30) DEFAULT NULL,
  contacto varchar(180) DEFAULT NULL,
  telefono varchar(30) DEFAULT NULL,
  correo varchar(150) DEFAULT NULL,
  grupo_cliente varchar(80) DEFAULT NULL,
  tipo_danio varchar(120) DEFAULT NULL,
  nro_panos varchar(30) DEFAULT NULL,
  horas_hombre varchar(30) DEFAULT NULL,
  departamento varchar(80) DEFAULT NULL,
  provincia varchar(80) DEFAULT NULL,
  distrito varchar(80) DEFAULT NULL,
  nro_cita varchar(50) DEFAULT NULL,
  man_rep varchar(20) DEFAULT NULL,
  subtipo_ot varchar(120) DEFAULT NULL,
  campania_externa varchar(120) DEFAULT NULL,
  recomendaciones text,
  KEY ix_orden_trabajo_nro_orden (nro_orden),
  KEY ix_orden_trabajo_fecha (fec_apertura),
  KEY ix_orden_trabajo_placa (placa)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Columnas segun backend/src/config/stagingImports.js -> clientes
CREATE TABLE IF NOT EXISTS stg_clientes_csv (
  cliente_documento varchar(30) DEFAULT NULL,
  tipo_documento varchar(30) DEFAULT NULL,
  tipo_cliente varchar(60) DEFAULT NULL,
  cliente_nombre varchar(180) DEFAULT NULL,
  apellido_contacto varchar(120) DEFAULT NULL,
  nombre_contacto varchar(120) DEFAULT NULL,
  direccion varchar(250) DEFAULT NULL,
  departamento varchar(80) DEFAULT NULL,
  provincia varchar(80) DEFAULT NULL,
  distrito varchar(80) DEFAULT NULL,
  telefono_fijo varchar(30) DEFAULT NULL,
  celular varchar(30) DEFAULT NULL,
  telefono_oficina varchar(30) DEFAULT NULL,
  red_privada varchar(60) DEFAULT NULL,
  email_personal varchar(150) DEFAULT NULL,
  email_trabajo varchar(150) DEFAULT NULL,
  email_see varchar(150) DEFAULT NULL,
  genero varchar(20) DEFAULT NULL,
  estado_civil varchar(30) DEFAULT NULL,
  fecha_nacimiento varchar(30) DEFAULT NULL,
  grupo_cliente varchar(80) DEFAULT NULL,
  forma_pago varchar(50) DEFAULT NULL,
  acepta_tratamiento varchar(10) DEFAULT NULL,
  KEY ix_stg_clientes_documento (cliente_documento)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Columnas segun backend/src/config/stagingImports.js -> clientes_servicio
CREATE TABLE IF NOT EXISTS stg_clientes_servicio_csv (
  concesionario varchar(120) DEFAULT NULL,
  local_nombre varchar(100) DEFAULT NULL,
  cliente_nombre varchar(180) DEFAULT NULL,
  contacto varchar(180) DEFAULT NULL,
  tipo_cliente varchar(60) DEFAULT NULL,
  telefono_fijo varchar(30) DEFAULT NULL,
  celular varchar(30) DEFAULT NULL,
  oficina varchar(30) DEFAULT NULL,
  correo varchar(150) DEFAULT NULL,
  asesor varchar(120) DEFAULT NULL,
  dni varchar(30) DEFAULT NULL,
  fecha_apertura varchar(30) DEFAULT NULL,
  placa varchar(20) DEFAULT NULL,
  grupo_servicio varchar(120) DEFAULT NULL,
  clase_ot varchar(120) DEFAULT NULL,
  tipo_ot varchar(120) DEFAULT NULL,
  kilometraje varchar(30) DEFAULT NULL,
  anio_fabricacion varchar(10) DEFAULT NULL,
  tratamiento_datos varchar(10) DEFAULT NULL,
  fecha_entrega varchar(30) DEFAULT NULL,
  grupo_cliente varchar(80) DEFAULT NULL,
  nro_ot varchar(50) DEFAULT NULL,
  subtipo_ot varchar(120) DEFAULT NULL,
  campania_externa varchar(120) DEFAULT NULL,
  marca varchar(80) DEFAULT NULL,
  modelo varchar(80) DEFAULT NULL,
  version varchar(150) DEFAULT NULL,
  color varchar(60) DEFAULT NULL,
  KEY ix_stg_clientes_servicio_placa (placa)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
